import pygame
import random
import math
from typing import List, Tuple
from enemy import enemy

#TODO: this class acts as a single room that is generated by a random floor generator. Implement both


class room:
    def __init__(self, id: int, x: int, y: int, enemies: bool):
        self.__roomID = int(id)
        self.__roomLayout = self.getRoom(id)
        self.__xCoord = x
        self.__yCoord = y
        self.__hostile: bool = enemies
        self.__enemies: List[Tuple[int,int,enemy]] = []  # x,y,Enemytype tuple((0, 0, None))

    def roomID(self) -> int:
        return self.__roomID

    def hostile(self) -> bool:
        return self.__hostile

    def getEnemies(self):
        return self.__enemies

    def xCoord(self) -> int:
        return self.__xCoord

    def yCoord(self) -> int:
        return self.__yCoord

    def setEnemy(self, x: int, y: int, new: enemy):
        for i in self.__enemies:
            if i[0] == x or i[1] == y:
                return
        self.__enemies.append(tuple((x, y, new)))

    def getRoom(self, id: int):
        blank = [[0] * 12 for i in range(9)]
        return blank



    def drawRoom(self):
        pass
        # use roomLayout to print out the room
        # 0 = blank
        # 1 = 4 doors empty
        # 2 = 3 doors (Up, Left, Down)
        # 3 = 2 doors (Up, Down)
        # 4 = 2 doors (Up, Left)
        # 5 = 2 doors (Down, Left)
        # 6 = End (Up)
        # 7 = End (Down)
        # 8 = End (Left)
        # 9 = 3 doors (Up, Right, Down)
        # 10 = 2 doors (Up, Right)
        # 11 = 2 doors (Down, Right)
        # 12 = End (Right)
        # 13 = Shop
        # 14 = Item Room
        # 15 = Bank
        # 16 = MinibossRoom
        # 17 = bossRoom
